config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /users/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  #ゲストログイン
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end


  scope module: :public do
    root to: 'homes#top'
    get '/about', to: 'homes#about'

    resources :lists, only: %i[new create index destroy show edit update] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    resources :users, only: %i[index show edit update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers' ,as: 'followers'
      member do
      get :favorites
      end
    end
    
    get 'searches/search' => "searches#search"
    resources :chats, only: [:show, :create]
  end

  namespace :admin do
    root to: 'lists#index'
    resources :lists, only: %i[index show edit update destroy]
    resources :users, only: %i[index show]
  end

end

app/models/list.rb
class List < ApplicationRecord
 has_one_attached :image
 belongs_to :user
 has_many :post_comments, dependent: :destroy
 has_many :favorites, dependent: :destroy
 has_many :tags, dependent: :destroy
 geocoded_by :habitat
 after_validation :geocode

 validates :name, presence: true
 validates :image, presence: true
 validates :introduction, presence: true
 validates :habitat, presence: true


 def get_image
   unless image.attached?
     file_path = Rails.root.join('app/assets/images/no_image.jpg')
     image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
   end
     image
 end

 def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
 end

 # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @list = List.left_joins(:tags).where("lists.name LIKE ? OR lists.habitat LIKE ? OR lists.introduction LIKE ? OR tags.name LIKE ?", "#{word}", "#{word}", "#{word}", "#{word}").distinct
    elsif search == "forward_match"
      @list = List.left_joins(:tags).where("lists.name LIKE ? OR lists.habitat LIKE ? OR lists.introduction LIKE ? OR tags.name LIKE ?", "#{word}%", "#{word}%", "#{word}%", "#{word}%").distinct
    elsif search == "backward_match"
      @list = List.left_joins(:tags).where("lists.name LIKE ? OR lists.habitat LIKE ? OR lists.introduction LIKE ? OR tags.name LIKE ?", "%#{word}", "%#{word}", "%#{word}", "%#{word}").distinct
    elsif search == "partial_match"
      @list = List.left_joins(:tags).where("lists.name LIKE ? OR lists.habitat LIKE ? OR lists.introduction LIKE ? OR tags.name LIKE ?", "%#{word}%", "%#{word}%", "%#{word}%", "%#{word}%").distinct 
    else
      @list = List.all
    end
  end

end

app/controllers/admin/lists_controller.rb
class Admin::ListsController < ApplicationController
  def index
    @lists = List.page(params[:page]).per(6)
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
    @list = List.find(params[:id])
  end

  def destroy
    list = List.find(params[:id])
    if list.destroy
    redirect_to admin_user_path(list.user_id), notice: "削除されました"
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :image, :introduction, :habitat, :updated_at )
  end

end

app/helpers/admin/lists_helper.rb
module Admin::ListsHelper
end

app/views/shares/lists/_list.html.erb
<div class= "container">
<div class='row'>
<h2>投稿一覧</h2>
<div class="row row-cols-1 row-cols-md-3 g-4">
  <% lists.each do |list| %>
  <div class="col">
    <div class="card h-100">
      <%= link_to list_path(list.id) do %>
        <%= image_tag list.get_image, class:"card-img-top", style: 'width: 100%; height: 300px; object-fit: cover;' %>
      <% end %>
      <div class="card-body">
        <div class="row">
            <div class="col-2">
              <%= link_to user_path(list.user.id) do %>
              <%= image_tag list.user.profile_image, class:"profile_image my-3 rounded-circle"; %>
              <% end %>
            </div>
        </div>
        <h5 class="card-title">
        <%= link_to(list_path(list.id), class:"text-dark") do %>
                  <strong><i class="far fa-flag"></i><span><%= list.name %></span></strong>
                <% end %></h5>
        <p class="card-text">説明：<%= list.introduction.truncate(10) %></p>
        <p class="card-text">生息地：<%= list.habitat %></p>
        <p class="card-text">更新日: <%= list.updated_at.strftime('%Y/%m/%d') %> </p>
        <span><i class="fas fa-user"></i> By <%= link_to list.user.name, user_path(list.user.id), class:"item-text" %> ｜ </span>
        <span><%= link_to "#{list.post_comments.count}  コメント", list_path(list.id), class:"text-dark" %></span>
        <p id="favorite-<%= list.id %>">
        <%= render "public/favorites/favorites", list: list %>
        </p>
      </div>
    </div>
  </div>
  <% end %>
</div>
<%= paginate lists %>
 </div>
</div>