config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /users/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  #ゲストログイン
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end


  scope module: :public do
    root to: 'homes#top'
    get '/about', to: 'homes#about'

    resources :lists, only: %i[new create index destroy show edit update] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    resources :users, only: %i[index show edit update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers' ,as: 'followers'
      member do
      get :favorites
      end
    end
    
    get 'searches/search' => "searches#search"
    resources :chats, only: [:show, :create]
  end

  namespace :admin do
    root to: 'lists#index'
    resources :lists, only: %i[index show edit update destroy]
    resources :users, only: %i[index show]
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :profile_image
  
  has_many :lists, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  
  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  # DM画面で使う
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms
  
  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image
  end
  
   # フォローしたときの処理
  def follow(user_id)
  relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
  relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
  followings.include?(user)
  end
  #検索機能
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
  #ゲストログイン
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name ,presence: true, length: { minimum: 1, maximum: 20 }
  validates :email ,presence: true, uniqueness: true
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users = User.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
    @lists = @user.lists.page(params[:page]).per(6)
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :email)
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <h2 class="mt-4">ユーザー一覧</h2>
  </div>
  <div class="row">
    <div class="col-md-10 col-md-offset-1 mx-auto">
      <table class="table table-hover">
        <thead class="table-green">
          <tr>
            <th>ユーザー</th>
            <th>メールアドレス</th>
          </tr>
        </thead>
        <% @users.each do |user| %>
        <tbody>
          <tr>
            <td>
              <%= link_to admin_user_path(user) do %>
              <%= image_tag user.get_profile_image,class:'profile_image' %>
              <%= user.name %>
              <% end %>
            </td>
            <td><%= user.email %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
      <%= paginate @users %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>ユーザー情報</h2>
      <table class='table'>
        <tr><%= image_tag @user.get_profile_image, class:'profile_image', style: 'width: 100%; height: 250px; object-fit: cover;' %></tr>
        <tr>
	      <th>ユーザー</th>
	      <th><%= @user.name %></th>
        </tr>
        <tr>
	      <th>メールアドレス</th>
	      <th><%= @user.email %></th>
        </tr>
      </table>
    </div>
    <div class='col-md-8 offset-md-1'>
      <%= render '/admin/lists/lists', lists: @lists %>
    </div>
  </div>
</div>