config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /users/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  #ゲストログイン
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end


  scope module: :public do
    root to: 'homes#top'
    get '/about', to: 'homes#about'

    resources :lists, only: %i[new create index destroy show edit update] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    resources :users, only: %i[index show edit update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers' ,as: 'followers'
      member do
      get :favorites
      end
    end
    
    get 'searches/search' => "searches#search"
    resources :chats, only: [:show, :create]
  end

  namespace :admin do
    root to: 'lists#index'
    resources :lists, only: %i[index show edit update destroy]
    resources :users, only: %i[index show]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email ,presence: true, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :list
  validates_uniqueness_of :list_id, scope: :user_id

end

app/models/list.rb
class List < ApplicationRecord
 has_one_attached :image
 belongs_to :user
 has_many :post_comments, dependent: :destroy
 has_many :favorites, dependent: :destroy
 has_many :tags, dependent: :destroy
 geocoded_by :habitat
 after_validation :geocode

 validates :name, presence: true
 validates :image, presence: true
 validates :introduction, presence: true
 validates :habitat, presence: true


 def get_image
   unless image.attached?
     file_path = Rails.root.join('app/assets/images/no_image.jpg')
     image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
   end
     image
 end

 def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
 end

 # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @list = List.left_joins(:tags).where("lists.name LIKE ? OR lists.habitat LIKE ? OR lists.introduction LIKE ? OR tags.name LIKE ?", "#{word}", "#{word}", "#{word}", "#{word}").distinct
    elsif search == "forward_match"
      @list = List.left_joins(:tags).where("lists.name LIKE ? OR lists.habitat LIKE ? OR lists.introduction LIKE ? OR tags.name LIKE ?", "#{word}%", "#{word}%", "#{word}%", "#{word}%").distinct
    elsif search == "backward_match"
      @list = List.left_joins(:tags).where("lists.name LIKE ? OR lists.habitat LIKE ? OR lists.introduction LIKE ? OR tags.name LIKE ?", "%#{word}", "%#{word}", "%#{word}", "%#{word}").distinct
    elsif search == "partial_match"
      @list = List.left_joins(:tags).where("lists.name LIKE ? OR lists.habitat LIKE ? OR lists.introduction LIKE ? OR tags.name LIKE ?", "%#{word}%", "%#{word}%", "%#{word}%", "%#{word}%").distinct 
    else
      @list = List.all
    end
  end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :list
  
  validates :comment, presence: true, length: { maximum: 140 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :list
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :profile_image
  
  has_many :lists, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  
  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  # DM画面で使う
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms
  
  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image
  end
  
   # フォローしたときの処理
  def follow(user_id)
  relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
  relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
  followings.include?(user)
  end
  #検索機能
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
  #ゲストログイン
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name ,presence: true, length: { minimum: 1, maximum: 20 }
  validates :email ,presence: true, uniqueness: true
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  
  def after_sign_in_path_for(resource)
    lists_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/lists_helper.rb
module Admin::ListsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p class="color-olive text-center mt-3">CopyRight Insect_lovers_comunity_site</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <div class='row __nav w-100 align-items-center'>
      <a class="navbar-brand" href="/">
        <div class="nav-logo">
          <%= image_tag "Logo_Insect_lovers.jpg", size: '80x80' %>
        </div>
      </a>
      <p class="main-title mt-2">あつまれ！昆虫愛好家の皆さん〜</p>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
            <p class="text-left mt-3" style="color: #ebea90; margin-left: 10%; font-size: 14px;">

              ようこそ、
              <% if current_user %>
                <%= current_user.name %>さん！
              <% end %>
            </p>
          <li>
            <%= link_to user_path(current_user),class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li>
            <%=  link_to users_path,class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i> Users
            <% end %>
          </li>
          <li>
            <%=  link_to lists_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i> lists
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> Log out
            <% end %>
          </li>

        <% elsif admin_signed_in? %>
          <p class="text-left mt-3" style="color: #ebea90; margin-left: 10%; font-size: 14px;">
              ようこそ、管理人さん！
          </p>
          <li>
            <%=  link_to admin_users_path,class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i> Users
            <% end %>
          </li>
          <li>
            <%=  link_to admin_lists_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i> lists
            <% end %>
          </li>
          <li>
            <%= link_to destroy_admin_session_path, method: :delete,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> Log out
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li>
            <%= link_to about_path,class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i> About
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i> Sign up
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> Log in
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
   </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InsectLovers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/4173c59b63.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-olive">
    <%= render 'layouts/header' %>
     <main>
        <p id="notice"><%= notice %></p>
        <div class="d-flex justify-content-center mb-2">
          <%= render 'public/searches/form' %>
        </div>
     <%= yield %>
     </main>
    <%= render 'layouts/footer' %>
  </body>
</html>